### ISSUE TITLE
Modify Usecase

### ISSUE THREAD

**Issue by thkim0402** [thkim0402/Mobile-Software-2019-Glass-of-Da-vinci#3]

**Comment by thkim0402** [comment]
기능요약
1. 폭탄주 제조 기능
2. 가지고 있는 술을 입력하면 가능한 레시피 보여주기
3. 커스텀 폭탄주 제조
4. 랭킹시스템(명예의 전당)
5. 댓글 및 좋아요

**Comment by elementrix** [comment]
사용자 <->앱
1. 자신이 원하는 술 검색 <-> 폭탄주 제조 방법 
2. 자신이 가지고 있는 술 입력 <-> 가능한 폭탄주 목록
3. 주종 선택+비율선택 <-> 커스텀 폭탄주 업로드
4.  <- 명예의 전당 폭탄주 추천
5. 좋아요 및 추천 ->

**Comment by thkim0402** [comment]
앱 <-> 서버(DB)
1. 사용자 ID, 비밀번호 등 개인정보 제공 <-> 정보 등록 및 관리
2. 댓글, 커스텀 레시피 및 좋아요 데이터 제공 <-> 순위별 정렬

**Comment by elementrix** [comment]
검색기능이 어떻게 이루어 지는지 모르겠네
